// IndexNow key file. IndexNow is the open protocol that Bing, Yandex,
// Seznam, Naver, and Yep use to receive instant URL-changed pings —
// faster than waiting for re-crawl. Google does not yet participate but
// has not deprecated either.
//
// Why a default key is hardcoded:
//   IndexNow keys are deliberately PUBLIC — search engines GET this
//   file to verify ownership, so it ships in the static asset surface
//   anyway. Hardcoding the user's generated key as the default means
//   the protocol works on first deploy without any Vercel env config.
//
// Override path:
//   Set NEXT_PUBLIC_INDEXNOW_KEY in Vercel env to rotate the key
//   without a code deploy. The override wins over the default.
//
// To rotate:
//   1. Generate a new key at https://www.bing.com/indexnow#implementation
//   2. Drop into Vercel → Settings → Environment Variables → NEXT_PUBLIC_INDEXNOW_KEY
//   3. Redeploy (or wait for the next deploy).

import { NextResponse } from "next/server";

export const dynamic = "force-static";
export const revalidate = false;

// Default IndexNow key — generated by the site owner at
// https://www.bing.com/indexnow#implementation. Public by design.
const DEFAULT_KEY = "fd368c2ed2b146b08786d891a327f465";

export function GET() {
  const key = process.env.NEXT_PUBLIC_INDEXNOW_KEY ?? DEFAULT_KEY;
  return new NextResponse(key, {
    status: 200,
    headers: {
      "content-type": "text/plain; charset=utf-8",
      // Long cache; rotation requires a redeploy anyway.
      "cache-control": "public, max-age=3600",
    },
  });
}
