// QUOTES — 365 short aphorisms in the "Compiled Thought" studio voice.
// One per UTC day-of-year so every visitor sees the same line on the
// same day. Picked by `QuoteOfTheDay` via a deterministic index, then
// copyable from the footer. New entries should stay short, opinionated,
// and observation-first — never imperative for its own sake.

export const QUOTES: string[] = [
  "Build like you're carving — every line either lifts or cuts.",
  "Slow scrolls reveal what fast ones can't.",
  "A grid is not a cage; a grid is a tide pool.",
  "Type breathes. Let it.",
  "If the cursor doesn't enjoy itself, no one will.",
  "Every shader is a love letter to a math you didn't write.",
  "Design for the curious. The hurried will get the same payoff.",
  "Motion has weight. Pretend it costs you something.",
  "A page is a room. Don't slam doors.",
  "An edge case is just a story you haven't told yet.",
  "Your portfolio is a museum of opinions.",
  "Make it boring. Then make one thing strange.",
  "If it works on the first try, you wrote it twice.",
  "Pixels round to integers. Decisions don't.",
  "WebGL is a darkroom; the developer is the chemist.",
  "An animation is a sentence. Punctuate it.",
  "Whitespace is a co-author.",
  "Reduce until the brand is wearing only its bones.",
  "An interface should be confidently quiet.",
  "Performance is a kindness.",
  "If it isn't keyboard-accessible, it isn't finished.",
  "A loading state is its own design problem.",
  "Easings are personality tests.",
  "The cursor is your most-used component. Treat it like one.",
  "First scroll, last impression.",
  "A bug is a brief from the system.",
  "Write commits as if they'll be read by an alien archaeologist.",
  "Add a delight; remove a friction. That's the trade.",
  "The web is the only medium where you can ship a fix mid-tour.",
  "Edge cases are the corners of a building. They define the shape.",
  "Make the empty state earn its keep.",
  "Microcopy is the team-mate that never goes home.",
  "Latency is grief. Reduce it where you can.",
  "If the hover is the moment, build a moment for the hover.",
  "Render once; remember always.",
  "Type at body weight. Heads at conviction.",
  "Atoms first. Then molecules. Then mood.",
  "Iterate at the speed of doubt, not the speed of confidence.",
  "A focused state is a portrait, not a hint.",
  "Audit your tooltips like you audit your tweets.",
  "A canvas without intent is a screensaver.",
  "Test every weight at every size.",
  "The hardest part of UI is naming.",
  "Trust the body copy. The headline is just bait.",
  "Build for the network you don't have.",
  "Keep your dev tools open. The site is talking.",
  "The right radius makes the wrong button feel right.",
  "Light is data. Use it like a prop, not a ghost.",
  "A grid bug is the project's astrology — it explains everything.",
  "Don't ship; finish.",
  "When you can't sleep, ship a fix; when you can, ship a feature.",
  "Cursor lag is a posture. Fix the posture.",
  "Every metric you don't measure measures you back.",
  "The future is mostly written in lowercase.",
  "Loading is a chance to make a friend.",
  "If a component has six props, it has two components.",
  "Bigger letters do not mean bigger ideas.",
  "Don't let the hero feel lonely.",
  "A great cursor knows when to disappear.",
  "MMXXVII is just a year. Make it count anyway.",
  "Beauty is fast.",
  "Defaults are forever.",
  "Care is the only feature that ages well.",
  "The studio is shipping.",

  // 65–120 · typography, hierarchy, kinetic type
  "Kerning is opinion held very, very still.",
  "A baseline is a horizon. Set it once and stop flinching.",
  "Display type is the brand wearing its outdoor coat.",
  "Italic is a tilt; oblique is a slouch. They're not the same.",
  "Tracking too tight reads angry; tracking too loose reads bored.",
  "Leading is the air the sentence breathes between heartbeats.",
  "Numerals are a kind of punctuation — small caps for math.",
  "An ampersand is a tiny logo. Audit it like one.",
  "A drop cap is a doorman, not a decoration.",
  "If the type doesn't scale, you don't have a system; you have a poster.",
  "Variable fonts are the difference between a noun and a verb.",
  "A wordmark is a face. Don't make it smirk at every size.",
  "Two typefaces is a duet. Three is a crowd.",
  "Hyphens are politicians; em-dashes are dramatists.",
  "Set body copy first. Headlines just react to it.",
  "Pull-quotes are the chorus of an article. Don't oversing them.",
  "If you can't read the navigation at one glance, the page is shouting.",
  "An H1 sets temperature. An H2 sets pace.",
  "Numerals make any layout look more confident.",
  "Optical sizes are kinder than weight axes.",
  "The widest character in your font is the room your column was built for.",
  "An eyebrow line is the page clearing its throat.",
  "A capital letter is a small monument; spend them carefully.",
  "A long word in a short column is a confession.",
  "Set caption smaller than body, and italic only if you'd whisper it.",
  "Don't fake bold. Get the bold cut.",
  "A typeface is a building. A weight is a doorway.",
  "Reduce the type scale until at least one size is missing. You won't miss it.",
  "The footer's typeface should grin, not glare.",
  "Mono is honest. Use it when you're holding a receipt.",
  "Centered display type wants a reason. Justified body copy wants a margin.",
  "A pull-quote two sizes up reads as an argument.",
  "Stretching letters is shouting in a foreign accent.",
  "Caps for taxonomy. Lowercase for personality.",
  "Tabular numerals are a quiet superpower.",
  "Letter-spacing is a haircut. Get it right and no one notices.",
  "The em-dash earns its keep on this site three times an hour.",
  "An italic in a sans-serif is a sigh. Use it when you mean it.",
  "Set captions in oldstyle figures. Set data in tabular.",
  "Hairlines flatter, but only on retina. Honor the audience's device.",
  "Don't justify body copy on the web. Pretend you have a typesetter.",
  "Set everything in two columns once a year, just to remember what you lost.",
  "Read every headline aloud before shipping. The bad ones declare themselves.",
  "Use small caps for the label, never for the lead.",
  "The font hierarchy is the website's posture.",
  "Set the page in body copy. Style decides what to lift.",
  "Width axis is the camera angle. Weight axis is the lighting.",
  "Adopt a swashy alternate once a year. Then refund it.",
  "Numerals have temper. Old-style cools the page; lining warms it up.",
  "Headlines reward concision. Subheads reward specificity.",
  "Don't write a hero headline you can't read at 12px.",
  "Letterforms remember their history. Watch them age in real time.",
  "If italics are doing your tonal work, slow down.",
  "A masthead is a treaty. Sign it twice and live with the consequences.",
  "Set every level of the hierarchy to read in dim light.",
  "When your body copy doesn't need leading, change body copy.",

  // 120–180 · motion, animation, easings, scroll
  "Motion is the difference between language and choreography.",
  "If a transition needs an explanation, rebuild it.",
  "Easings are nouns. Choose one, then stop browsing them.",
  "300ms is the length of a thought. Don't outlast it.",
  "A spring that doesn't damp is a lecture nobody asked for.",
  "Stagger one element too many and the room starts murmuring.",
  "Scroll-driven motion is a kindness or a costume.",
  "If the page can't sit still, it isn't done thinking.",
  "Reduced motion is not an obstacle; it's an audience.",
  "Choreograph entrance. Earn the exit.",
  "An animation that loops is asking to be ignored. Let it.",
  "Bounce is a flavor. A whole page of it is a buffet.",
  "Easing is taste. Spring physics is opinion.",
  "Hover lifts are tiny doorbells. Don't let them ring all day.",
  "Stagger by 40ms; the eye believes it.",
  "Don't animate what won't survive the first redesign.",
  "Pinning is borrowing real estate. Pay it back with content.",
  "Parallax is a flavor; layer it like garlic, not like icing.",
  "A skeleton state should breathe, not pulse like a panic attack.",
  "If you scroll and nothing changes, the page isn't pinned. It's stuck.",
  "Inertia is a luxury. Use Lenis like a chauffeur.",
  "Smooth scroll is a contract. Don't break it for novelty.",
  "Cubic-bezier(0.22, 1, 0.36, 1) is the easing of grown-ups.",
  "Don't animate opacity and transform on the same element without thinking.",
  "Frame budgets are emotional. Anything over 8ms feels honest, over 16 feels nervous.",
  "Confetti is consent the user revokes after the first time.",
  "A modal should slide in like a guest, not a delivery van.",
  "Stagger entries forward, never backward. Reading direction is the rule.",
  "Hover trails are kerosene; spend them on landing pages, not docs.",
  "If a CSS transition will do, it will do.",
  "Reactive blur is a vibe; non-reactive blur is a screenshot.",
  "Don't animate the same property twice in one keyframe.",
  "If the timeline is longer than the user's attention, the timeline is wrong.",
  "Use will-change like a hot pad — for short, hot moments only.",
  "Motion design is choreographing absence. The empty frames matter most.",
  "The best transition is the one the user re-traces in memory.",
  "Spring overshoot is a smile. Don't smile in every paragraph.",
  "A scrub bar is a film strip; don't make it a screenshot grid.",
  "Animate the consequences, not the causes.",
  "Page transitions are negotiations between two URLs. Be diplomatic.",
  "Motion should feel weighted, not greased.",
  "Don't synchronize motion across devices; sync it across moods.",
  "A loading bar that lies is a relationship that breaks.",
  "Damping is the unsung hero of frontend physics.",
  "A scroll-snap that fights the user is a tantrum, not a feature.",
  "Easings tell time the way wine tells weather.",
  "A site without rest beats are a site without rhythm.",
  "Don't fade where you could lift.",
  "Don't lift where you could pulse.",
  "If your reveal looks like a curtain, ask if it's also a wall.",
  "Animate states, not values. Values are noise; states are meaning.",
  "Pin generously. Unpin promptly.",
  "A great animation tells the user where they were, where they are, and where they're going.",
  "Inertia teaches patience to designers and pixels alike.",
  "Don't animate the cursor. The cursor is animating the user.",
  "Match motion to copy. Confident copy gets confident easings.",
  "Skeletons are placeholders, not decoration. Replace them honestly.",
  "Loading animations should hum, not chant.",
  "The first frame of any motion is a promise. Read it twice.",

  // 180–240 · webgl / shaders / canvas / 3D
  "A shader is a question. A material is the answer.",
  "If you've written more than three uniforms, you have a system.",
  "Normalize before you sample. Future-you will say thanks.",
  "fbm is a chord. Use it like one.",
  "A noise field is a mood ring with attitude.",
  "Don't ship a shader you can't read at 4am.",
  "Raymarching is patience compiled into a triangle.",
  "Signed-distance fields are diagrams disguised as geometry.",
  "Don't fight the GPU. Fight the artist who blamed the GPU.",
  "Curl noise is jazz. fbm is folk. Both belong on the bill.",
  "Roughness is a personality trait.",
  "Specular is the smile of a surface.",
  "Anisotropic highlights are how hair admits it's been combed.",
  "PBR is honesty. Hand-painting is theater. Decide the program.",
  "An IBL is a small theater built into your geometry.",
  "If your hero shader compiles in 6 lines, write a 7-line one and delete the longest.",
  "Light is the first interaction. Treat it as UX.",
  "Bake your normals. Stop pretending you'll iterate.",
  "Mip levels are dramatic — pick the right one for the scene's mood.",
  "Procedural is not free; it's just deferred-cost art direction.",
  "GLSL is poetry; you ration the lines.",
  "Don't sample twice what you could blur once.",
  "Texture compression is a budget conversation with the future.",
  "Three.js is a sandbox; raw WebGL is the workshop.",
  "If you can ship a custom shader, you should.",
  "A particle system without art direction is rain.",
  "A particle system with art direction is weather.",
  "Reduce uniform count before reducing fps.",
  "Don't render off-screen. The browser already does.",
  "GPGPU is fine. Show me your error handling first.",
  "Instancing is the only honest answer to a million things.",
  "Don't write a shader that needs a tutorial. Write a tutorial in the shader.",
  "Procedural noise compresses better than a JPEG of the same thing.",
  "DPI is a budget. Spend it where the camera lingers.",
  "Frame-rate is etiquette.",
  "A GPU never lies. The browser sometimes does.",
  "Shadow softness is the personality of a sun.",
  "Volumetric fog is patience with a budget.",
  "Don't reach for postprocessing first. Reach for materials first.",
  "Bloom is sugar. Don't season the whole meal.",
  "A god ray is a flashlight in the room. Use it sparingly.",
  "Depth-of-field is a confession of where you want the eye.",
  "Motion blur is the only honest answer to fast motion.",
  "Don't write a fragment shader you wouldn't read aloud.",
  "Sample your noise three octaves deep, then stop.",
  "If your vertex shader is slow, your geometry is wrong.",
  "Premultiplied alpha is a relationship; understand it before signing.",
  "Color in linear; deliver in sRGB; never debug in either.",
  "Use a tone-mapper. Don't crush highlights for fun.",
  "If your skybox is a JPEG, your day is a postcard.",
  "Don't animate inside the shader if you can animate the uniform.",
  "Lighting tells the time. Composition tells the date.",
  "Tessellation is taste. Bevel is biology.",
  "Reflection probes are a budget conversation with your viewer.",
  "The cheapest material is the one you don't put on screen.",
  "Curve UVs once. Bend pixels twice.",
  "Don't pick a noise. Layer two.",
  "Anti-aliasing is the difference between art and pixel art.",
  "MSAA is the only respectable shortcut.",
  "Order-independent transparency is a myth; depth peeling is a religion.",

  // 240–300 · craft, code, naming, refactor, bugs
  "Refactor when you understand. Rewrite when you don't.",
  "Naming is the only design choice you can't sleep on.",
  "Tests are kind to future maintainers; opinions are not.",
  "If you can't draw the data flow on a napkin, the code is too clever.",
  "A long function is fine; a long function with a side effect is a crime scene.",
  "Premature optimization is a personality trait. Don't make it yours.",
  "Avoid global state like you avoid borrowing money from family.",
  "Read the code you wrote last year as if it were someone else's. It is.",
  "Comments age badly. Names age forever.",
  "A type system is a conversation with future you.",
  "A pull request is a love letter to maintenance.",
  "Don't ship a feature you can't draw the menu of.",
  "If you can't delete it, you don't own it.",
  "An interface is a promise. A type is the lawyer.",
  "Tests describe; assertions enforce.",
  "Mocks are bookmarks, not the book.",
  "Read your stack trace from the bottom up. The truth lives there.",
  "Logs are letters from the system to its therapist.",
  "Stack traces are the script of an unrehearsed play.",
  "An exception is a bug confessing.",
  "Delete a util every Friday. Make room for the next bad idea.",
  "Refactor in the same commit you understand it.",
  "If two functions disagree on the same input, you have a bug or a design.",
  "Don't optimize before you measure; don't measure before you understand.",
  "Cache is a contract you'll regret.",
  "Memoization is borrowing time. Pay it back with invalidation.",
  "A library is a vote of confidence in someone else's API.",
  "Read the docs twice. The third pass is muscle memory.",
  "Don't add an abstraction without a price tag.",
  "Lint warnings are letters from people who slept on the code.",
  "Don't ship a flag. Decide.",
  "Boolean parameters are interview questions you failed.",
  "Tests are the only documentation that fails loudly.",
  "Default everything. Then prove the defaults are wrong.",
  "Pure functions are gifts to your future debugger.",
  "Side effects are tickets to your future self's inbox.",
  "Idempotence is the property you didn't know you needed.",
  "A retry policy is a kindness with a fuse.",
  "Don't trust input. Don't insult the user.",
  "Validation is the politest gatekeeping.",
  "An error message is a piece of UX writing.",
  "Logs without context are letters without addresses.",
  "Don't deploy on a Friday unless Friday is for adventure.",
  "Migrations are promises you write to your database.",
  "Migrations are also love letters to your future on-call self.",
  "An off-by-one error is the universe asking you to slow down.",
  "Time zones are a feature you keep accidentally building.",
  "Mutexes are referees. Don't argue with referees.",
  "Async/await is a contract with the event loop. Honor it.",
  "Don't catch what you can't fix.",
  "A monorepo is a cathedral; a polyrepo is a market. Pick by mood.",
  "Names should age like wine, not lettuce.",
  "An API is a stage. Design what the audience can see.",
  "A schema is a treaty. Migrations are negotiations.",
  "If you're tempted to write a meta-programming layer, write a docstring instead.",
  "Yak-shaving is sometimes the work. Notice when it stops being.",
  "Refactor pairs are mentorship in disguise.",
  "Inline the function before you abstract it.",
  "Read the test before the implementation; understand the contract first.",

  // 300–365 · craft, taste, sustaining a practice
  "Taste is a discipline. Practice it daily.",
  "Curation is a form of generosity.",
  "Steal generously, attribute relentlessly.",
  "Build a craft worth being copied. Then move.",
  "Originality is sustained attention to obvious places.",
  "Burnout is unspent attention. Spend some, refill the rest.",
  "Rest is the only feature that compounds.",
  "Take a sabbath from the screen once a week. The site survives.",
  "An idea worth writing down is worth defending in public.",
  "Write the post. Then ship the feature.",
  "A studio is a habit pretending to be an address.",
  "The portfolio is the studio's mirror; don't dress for it twice.",
  "Send the email. The project finds the way.",
  "A small client is a future case study with patience.",
  "A great deck is a confidence the room can read.",
  "Briefs are clay; you can shape them or fire them.",
  "Read the audience before reading the brief.",
  "Stand-ups are confessionals. Be brief.",
  "Critique is a gift. Wrap it nicely.",
  "Defend the decision you'd defend at 3am.",
  "Ship at 80%. The other 20% is a maintenance plan.",
  "Process is taste, rehearsed.",
  "Discovery is letting the brief tell you what it doesn't know.",
  "An invoice is a portrait of how you value your time.",
  "Don't undercut your own rates. The market notices.",
  "Send a follow-up. Eighty percent of yes lives there.",
  "Confidence in the work is humility in the brief.",
  "A retainer is a relationship; price it like one.",
  "Negotiate scope, not principle.",
  "Saying no clears a runway for the right yes.",
  "A signature is a small ceremony at the bottom of every email.",
  "Reply within a day. Replying late is its own design choice.",
  "Document while you're proud of the work.",
  "A studio diary is cheaper than therapy and almost as honest.",
  "Read one thing outside your stack every week.",
  "Adjacent disciplines are where the original ideas live.",
  "Watch movies for camera moves; watch books for line breaks.",
  "Study cathedral windows on a museum day.",
  "A folio is a museum of confidence.",
  "Saturday is for the lab. Monday is for the deck.",
  "Sleep is the only optimization with no trade-offs.",
  "Walk when stuck. The screen is not the room.",
  "Move your tools. Move your taste.",
  "Don't outgrow your tools; outsmart them.",
  "Reuse a sketch you didn't ship last month. There was a reason.",
  "The right project pays you twice — in money and in confidence.",
  "Tend your tools. They tend you back.",
  "An archive is the studio remembering itself.",
  "A changelog is a self-portrait drawn in patches.",
  "Re-read your contracts every year. Past-you was negotiating without context.",
  "Build the back-office before the brand outgrows it.",
  "A studio name is a promise you renew each January.",
  "Calendar blocking is a form of choreography.",
  "Don't multitask the work. Multitask the recovery.",
  "Mentorship is taste, distributed.",
  "Junior questions sharpen senior answers.",
  "Bring the team a problem with two solutions. Pick neither.",
  "Hire for taste; train for stack.",
  "Mentor by demonstrating. Then by listening. Then by leaving.",
  "Tell the room what you noticed; ask what they noticed too.",
  "Be specific about what you praise. Be even more specific about what you cut.",
  "Speak to the work; never to the worker.",
  "Receipts of generosity stay in the room long after the deck closes.",
  "If a client lights up on a phrase, write it down. That's the brand.",
  "A reference is a hypothesis. Build to disprove it.",
  "Send the rough cut early; it earns the polish later.",
  "Two senior people in a room beat ten juniors. Then mentor the juniors anyway.",
];
